#!/usr/bin/env node
/**
 * Generates docs/CODE.md — a single document containing every source file.
 * Runs automatically before every build/dev via the npm "predev"/"prebuild"
 * hooks, so the code document is always in sync with the code itself.
 */
import { promises as fs } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const INCLUDE_DIRS = ["app", "components", "lib", "scripts"];
const INCLUDE_FILES = [
  "package.json",
  "tsconfig.json",
  "next.config.mjs",
  "tailwind.config.ts",
  "postcss.config.mjs",
  ".env.local.example",
  "start.bat",
  "start.sh",
  "CLAUDE.md",
];
const EXT_LANG = {
  ".ts": "ts",
  ".tsx": "tsx",
  ".mjs": "js",
  ".json": "json",
  ".css": "css",
  ".bat": "bat",
  ".sh": "bash",
  ".md": "markdown",
  ".example": "bash",
};

async function walk(dir) {
  const out = [];
  for (const e of await fs.readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...(await walk(p)));
    else out.push(p);
  }
  return out;
}

const files = [];
for (const d of INCLUDE_DIRS) {
  try {
    files.push(...(await walk(path.join(root, d))));
  } catch {
    /* dir may not exist */
  }
}
for (const f of INCLUDE_FILES) {
  try {
    await fs.access(path.join(root, f));
    files.push(path.join(root, f));
  } catch {
    /* optional */
  }
}
files.sort();

let md = `# 24H Work Dashboard — Full Source Code

> AUTO-GENERATED by \`scripts/generate-docs.mjs\` — do not edit by hand.
> Regenerated on every \`npm run dev\` / \`npm run build\` (and via \`npm run docs\`).
> Generated: ${new Date().toISOString()} · Files: ${files.length}

`;

for (const f of files) {
  const rel = path.relative(root, f).replace(/\\/g, "/");
  const ext = path.extname(f);
  const lang = EXT_LANG[ext] ?? "";
  const body = await fs.readFile(f, "utf8");
  md += `\n---\n\n## \`${rel}\`\n\n\`\`\`${lang}\n${body.trimEnd()}\n\`\`\`\n`;
}

await fs.mkdir(path.join(root, "docs"), { recursive: true });
await fs.writeFile(path.join(root, "docs", "CODE.md"), md, "utf8");
console.log(`docs/CODE.md generated (${files.length} files, ${(md.length / 1024).toFixed(0)} KB)`);